# Regenerates articles/articles.js from every .txt file in the articles folder.
# Workflow:
#   1. Add or edit a .txt file inside the articles folder
#   2. Double-click this script (or run it with PowerShell)
#   3. Open index.html — articles will load without needing a local server

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$articlesDir = Join-Path $root 'articles'

if (-not (Test-Path $articlesDir)) {
    Write-Host "Folderul 'articles' nu a fost gasit la $articlesDir" -ForegroundColor Red
    exit 1
}

$files = Get-ChildItem -Path $articlesDir -Filter '*.txt' -File | Sort-Object Name

$articles = @()
foreach ($f in $files) {
    $raw = Get-Content -Path $f.FullName -Raw -Encoding UTF8
    if ($null -eq $raw) { $raw = '' }

    $title = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)

    $description = ''
    $match = [regex]::Match($raw, '\[description\]\s*\{([\s\S]*?)\}', 'IgnoreCase')
    if ($match.Success) {
        $description = $match.Groups[1].Value.Trim()
    }

    $fullText = [regex]::Replace($raw, '\[description\]\s*\{[\s\S]*?\}', '', 'IgnoreCase').Trim()

    $articles += [pscustomobject]@{
        title       = $title
        description = $description
        fullText    = $fullText
    }
}

# Force an array even when there is a single article.
$json = ConvertTo-Json -InputObject @($articles) -Depth 5

$output = @"
// Auto-generated by build-articles.ps1 — do not edit manually.
// Run build-articles.ps1 again after adding or changing a .txt file in the articles folder.
window.ARTICLES = $json;
"@

$outPath = Join-Path $articlesDir 'articles.js'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, $output, $utf8NoBom)

Write-Host ("S-au generat {0} articole in {1}" -f $articles.Count, $outPath) -ForegroundColor Green
